/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HostRouteImport } from './routes/host'
import { Route as LoggerRouteImport } from './routes/logger'
import { Route as MatchLoggerRouteImport } from './routes/match-logger'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as ProfileRouteImport } from './routes/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggerRoute = LoggerRouteImport.update({
  id: '/logger',
  path: '/logger',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchLoggerRoute = MatchLoggerRouteImport.update({
  id: '/match-logger',
  path: '/match-logger',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/host': typeof HostRoute
  '/logger': typeof LoggerRoute
  '/match-logger': typeof MatchLoggerRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/host': typeof HostRoute
  '/logger': typeof LoggerRoute
  '/match-logger': typeof MatchLoggerRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/host': typeof HostRoute
  '/logger': typeof LoggerRoute
  '/match-logger': typeof MatchLoggerRoute
  '/matches': typeof MatchesRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/home'
    | '/host'
    | '/logger'
    | '/match-logger'
    | '/matches'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/home'
    | '/host'
    | '/logger'
    | '/match-logger'
    | '/matches'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/home'
    | '/host'
    | '/logger'
    | '/match-logger'
    | '/matches'
    | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  HomeRoute: typeof HomeRoute
  HostRoute: typeof HostRoute
  LoggerRoute: typeof LoggerRoute
  MatchLoggerRoute: typeof MatchLoggerRoute
  MatchesRoute: typeof MatchesRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logger': {
      id: '/logger'
      path: '/logger'
      fullPath: '/logger'
      preLoaderRoute: typeof LoggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-logger': {
      id: '/match-logger'
      path: '/match-logger'
      fullPath: '/match-logger'
      preLoaderRoute: typeof MatchLoggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  HomeRoute: HomeRoute,
  HostRoute: HostRoute,
  LoggerRoute: LoggerRoute,
  MatchLoggerRoute: MatchLoggerRoute,
  MatchesRoute: MatchesRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
