/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BasicResultRouteImport } from './routes/basic-result'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HostRouteImport } from './routes/host'
import { Route as LoggerRouteImport } from './routes/logger'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefereeRouteImport } from './routes/referee'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicResultRoute = BasicResultRouteImport.update({
  id: '/basic-result',
  path: '/basic-result',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggerRoute = LoggerRouteImport.update({
  id: '/logger',
  path: '/logger',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefereeRoute = RefereeRouteImport.update({
  id: '/referee',
  path: '/referee',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-result': typeof BasicResultRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/host': typeof HostRoute
  '/logger': typeof LoggerRoute
  '/matches': typeof MatchesRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/referee': typeof RefereeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-result': typeof BasicResultRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/host': typeof HostRoute
  '/logger': typeof LoggerRoute
  '/matches': typeof MatchesRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/referee': typeof RefereeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basic-result': typeof BasicResultRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/host': typeof HostRoute
  '/logger': typeof LoggerRoute
  '/matches': typeof MatchesRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/referee': typeof RefereeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basic-result'
    | '/discover'
    | '/home'
    | '/host'
    | '/logger'
    | '/matches'
    | '/player'
    | '/profile'
    | '/referee'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basic-result'
    | '/discover'
    | '/home'
    | '/host'
    | '/logger'
    | '/matches'
    | '/player'
    | '/profile'
    | '/referee'
  id:
    | '__root__'
    | '/'
    | '/basic-result'
    | '/discover'
    | '/home'
    | '/host'
    | '/logger'
    | '/matches'
    | '/player'
    | '/profile'
    | '/referee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicResultRoute: typeof BasicResultRoute
  DiscoverRoute: typeof DiscoverRoute
  HomeRoute: typeof HomeRoute
  HostRoute: typeof HostRoute
  LoggerRoute: typeof LoggerRoute
  MatchesRoute: typeof MatchesRoute
  PlayerRoute: typeof PlayerRoute
  ProfileRoute: typeof ProfileRoute
  RefereeRoute: typeof RefereeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-result': {
      id: '/basic-result'
      path: '/basic-result'
      fullPath: '/basic-result'
      preLoaderRoute: typeof BasicResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logger': {
      id: '/logger'
      path: '/logger'
      fullPath: '/logger'
      preLoaderRoute: typeof LoggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referee': {
      id: '/referee'
      path: '/referee'
      fullPath: '/referee'
      preLoaderRoute: typeof RefereeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicResultRoute: BasicResultRoute,
  DiscoverRoute: DiscoverRoute,
  HomeRoute: HomeRoute,
  HostRoute: HostRoute,
  LoggerRoute: LoggerRoute,
  MatchesRoute: MatchesRoute,
  PlayerRoute: PlayerRoute,
  ProfileRoute: ProfileRoute,
  RefereeRoute: RefereeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
